version: "3"
services:
  evaluate:
    env_file: .env
    volumes: 
     - ./output:/output:rw
    build:
      context: .
      args:
        param_expr: "$PARAM_EXPR"
        output_cmd:  bash -c " echo $$(( ${PARAM_EXPR} ))"
