version: "3"
services:
  evaluate:
    env_file: jenkins.env
    volumes: 
     - ${SETTING_OUTPUT_DIRECTORY}:/output:rw
    build:
      context: .
      args:
        ARG_PLATFORM: ${SETTING_PLATFORM}
